// auth.js
export const LOGOUT = 'LOGOUT'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const UPDATE_USER = 'UPDATE_USER'

// lang.js
export const SET_LOCALE = 'SET_LOCALE'

// property.js
export const MUTATION_DELETE_PROPERTY = 'MUTATION_DELETE_PROPERTY'
export const MUTATION_UPDATE_PROPERTY = 'MUTATION_UPDATE_PROPERTY'
export const MUTATION_SET_ALL_PROPERTY = 'MUTATION_SET_ALL_PROPERTY'
export const MUTATION_CREATE_PROPERTY = 'MUTATION_CREATE_PROPERTY'

// courses.js
export const MUTATION_DELETE_COURSE = 'MUTATION_DELETE_COURSE'
export const MUTATION_UPDATE_COURSE = 'MUTATION_UPDATE_COURSE'
export const MUTATION_SET_ALL_COURSE = 'MUTATION_SET_ALL_COURSE'
export const MUTATION_CREATE_COURSE = 'MUTATION_CREATE_COURSE'

// huntergroup.js
export const MUTATION_DELETE_HUNTERGROUP = 'MUTATION_DELETE_HUNTERGROUP'
export const MUTATION_UPDATE_HUNTERGROUP = 'MUTATION_UPDATE_HUNTERGROUP'
export const MUTATION_SET_ALL_HUNTERGROUP = 'MUTATION_SET_ALL_HUNTERGROUP'
export const MUTATION_CREATE_HUNTERGROUP = 'MUTATION_CREATE_HUNTERGROUP'

// hunters.js
export const MUTATION_DELETE_HUNTER = 'MUTATION_DELETE_HUNTER'
export const MUTATION_UPDATE_HUNTER = 'MUTATION_UPDATE_HUNTER'
export const MUTATION_SET_ALL_HUNTER = 'MUTATION_SET_ALL_HUNTER'
export const MUTATION_CREATE_HUNTER = 'MUTATION_CREATE_HUNTER'

// dogs.js
export const MUTATION_DELETE_DOG = 'MUTATION_DELETE_DOG'
export const MUTATION_UPDATE_DOG = 'MUTATION_UPDATE_DOG'
export const MUTATION_SET_ALL_DOG = 'MUTATION_SET_ALL_DOG'
export const MUTATION_CREATE_DOG = 'MUTATION_CREATE_DOG'

// dashboard
export const MUTATION_SET_DASHBOARD = 'MUTATION_SET_DASHBOARD'

// coursemetrics
export const MUTATION_SET_COURSEMETRICS = 'MUTATION_SET_COURSEMETRICS'

// dogperformance
export const MUTATION_SET_DOGPERFORMANCE = 'MUTATION_SET_DOGPERFORMANCE'

// mapcovey
export const MUTATION_SET_MAPCOVEY = 'MUTATION_SET_MAPCOVEY'